# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog | CKJ
email: ckj996@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a freshman at Xidian University.
  I'm interested in computer systems.
  I like open source, and I run Debian on my Pavilion 13.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ckj996.github.io" # the base hostname & protocol for your site
github_username:  ckj996

# Build settings
markdown: kramdown
